---
title: "Publications & Presentations"
---


```{r setup, include=FALSE,cache=FALSE}
####
# Add [bib] with the biblatex
###
library(knitr)
library(rmarkdown)
library(htmltools)

options(htmltools.dir.version = FALSE)

library(RefManageR)
articles <- ReadBib("papers/articles.bib", check = FALSE)
inproceedings <- ReadBib("papers/inproceedings.bib", check = FALSE)
presentations <- ReadBib("papers/others.bib", check = FALSE)
underreview <- ReadBib("papers/underreview.bib", check = FALSE)
books <- ReadBib("papers/books.bib", check = FALSE)
unpublished <- ReadBib("papers/unpublished.bib", check = FALSE)

BibOptions(check.entries = FALSE, style = "html", cite.style = "authortitle",
           bib.style = "authoryear",sorting="ydnt",max.names =10,dashed=FALSE)
# sort(bib,sorting="ydnt")
endcit <- "</cite></p>"
 
this_year <- as.numeric(format(Sys.Date(), "%Y"))
first_year <-  2000
source("common.R")

```

<br/> <br/>

# Books

```{r books,echo=F,results="asis",cache=F}
output(books, withbrackets = TRUE) 
```

<br/> <br/>

# Under review


```{r,echo=F,results="asis",cache=F}
output(underreview) 
```

<br/> <br/>

# Published (or accepted) in peer-reviewed journals


```{r articles-pub,echo=F,results="asis",cache=FALSE}
for(y in sort(unique(as.numeric(articles$year)), decreasing  = TRUE)){
    articles_y <- suppressMessages(articles[list(year=as.character(y))])
    if(length(articles_y)!=0){    
        cat(paste0("## ",as.character(y),"\n" )) 
        output(articles_y)  
    }
}    
```

<br/> <br/>

# Short peer-reviewed papers in conferences

```{r,echo=F,results="asis",cache=F}
for(y in sort(unique(as.numeric(inproceedings$year)), decreasing  = TRUE)){

    inproceedings_y <- suppressMessages(inproceedings[list(year=as.character(y))])
        output(inproceedings_y,withbrackets=TRUE)

}
```

# Unpublished manuscripts


```{r,echo=F,results="asis",cache=F}
output(unpublished) 
```

<br/> <br/>

# Conferences

```{r,echo=F,results="asis",cache=F}

for(y in sort(unique(as.numeric(presentations$year)),, decreasing  = TRUE)){

    presentations_y <- suppressMessages(presentations[list(year=as.character(y))])
    if(length(presentations_y)!=0){    
        cat(paste0("### ",as.character(y),"\n" ))  
        output(presentations_y)
    }
}
```
